In [80]:
import pandas as pd
import os
import numpy as np
import time

In [81]:
os.listdir("../datasets")

['all_feature_encoding.csv',
 'frequency_encoding.csv',
 'item_freq_vec.csv',
 'item_no_n_onehot.csv',
 'no_encoding.csv',
 'test_candidate_992.csv',
 'train_purchase.csv',
 'train_sessions_x.csv',
 'train_ses_vec_x_992.csv',
 'val_candidate_992.csv',
 'val_purchase.csv',
 'val_sessions_x.csv',
 'val_ses_vec_x_992.csv']

In [82]:
item_vec = pd.read_csv("../datasets/item_no_n_onehot.csv",index_col=0)
item_vec.set_index("item_id",inplace=True)
item_vec.head()

,10_147,10_159,10_184,10_217,10_22,10_287,10_361,10_407,10_464,10_561,...,68_1,69_1,6_1,70_1,71_1,72_1,73_1,7_1,8_1,9_1
item_id,,,,,,,,,,,,,,,,,,,,,
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.336008,1.071298,-0.264768,-0.172988,-0.145533,-0.423388,-0.987598,-0.117550,-0.278755,-0.072062
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.746646,-0.001409,-0.264768,-0.172988,-0.145533,-0.423388,1.072686,0.080247,-0.278755,-0.072062
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.243919,-0.199109,-0.264768,-0.172988,-0.145533,-0.423388,1.072686,1.393206,-0.278755,-0.072062
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.288110,-0.001409,-0.264768,-0.172988,-0.145533,-0.423388,-0.987598,0.366711,-0.278755,-0.072062
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.336008,-0.001409,-0.264768,-0.172988,-0.145533,-0.423388,1.072686,1.260205,-0.278755,-0.072062

In [84]:
test_ses_vec = pd.read_csv("../datasets/test_ses_vec_992.csv",index_col=0)
test_ses_vec

,10_147,10_159,10_184,10_217,10_22,10_287,10_361,10_407,10_464,10_561,...,68_1,69_1,6_1,70_1,71_1,72_1,73_1,7_1,8_1,9_1
26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.336008,0.778409,-0.264768,-0.172988,-0.145533,-0.423388,1.072686,1.260205,-0.278755,-0.072062
200,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-2.369569,4.285194,-1.059073,-0.691953,-0.582130,-1.693552,4.290745,-0.470198,-1.115018,-0.288247
205,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.374104,0.686881,-0.264768,-0.172988,-0.145533,0.964532,1.072686,1.260205,-0.278755,-0.072062
495,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.202060,0.170664,-0.264768,-0.172988,-0.145533,0.251816,1.072686,0.080247,-0.278755,-0.072062
521,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.057464,-0.001409,-0.264768,-0.172988,-0.145533,-0.742234,-0.642955,0.649764,-0.278755,-0.072062
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2319540,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.313225,0.778409,-0.264768,-0.172988,-0.145533,0.964532,1.072686,1.260205,-0.278755,-0.072062
2319570,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.634748,3.892045,-1.323841,-0.864941,-0.727663,-2.116940,5.363431,-0.587748,-1.393773,-0.360309
2319688,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.262590,-13.012742,-1.588609,-1.037930,-0.873195,-4.650341,6.436117,-8.767209,-1.672527,-0.432370
2319692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.336008,0.170664,-0.264768,-0.172988,-0.145533,-0.423388,1.072686,-1.454381,-0.278755,-0.072062
2319693,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.288725,13.109022,-8.053265,-6.919531,-5.821303,-10.333520,42.907448,3.721422,-11.150181,-2.882469

In [86]:
candidate = pd.read_csv("../datasets/test_candidate_992.csv",index_col=0)
candidate.head()

,10_147,10_159,10_184,10_217,10_22,10_287,10_361,10_407,10_464,10_561,...,68_1,69_1,6_1,70_1,71_1,72_1,73_1,7_1,8_1,9_1
item_id,,,,,,,,,,,,,,,,,,,,,
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.243919,-0.199109,-0.264768,-0.172988,-0.145533,-0.423388,1.072686,1.393206,-0.278755,-0.072062
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.336008,-0.001409,-0.264768,-0.172988,-0.145533,-0.423388,1.072686,1.260205,-0.278755,-0.072062
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.875985,0.778409,-0.264768,-0.172988,-0.145533,2.268051,1.072686,0.366711,-0.278755,-0.072062
19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.374104,-0.001409,2.272696,-0.172988,-0.145533,-0.423388,1.072686,0.649764,-0.278755,-0.072062
20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.675486,-1.744101,-0.264768,-0.172988,-0.145533,-0.423388,1.072686,1.393206,-0.278755,-0.072062

In [39]:
def inner_product(v1,v2):
    return sum(a*b for a, b in zip(v1, v2))

In [28]:
def cosine_similarity(v1,v2):
    dot = sum(a*b for a, b in zip(v1, v2))
    norm_a = sum(a*a for a in v1) ** 0.5
    norm_b = sum(b*b for b in v2) ** 0.5
    return dot / (norm_a*norm_b)

In [51]:
def eu_dist(v1,v2):
    return np.sqrt(sum((v1-v2)**2))

In [95]:
def similarity_encoding(_session_df,_candi_arr,_item_df):
    '''
    given session,candidate(arr),item_df return similarity for every session to all candidate
    '''
    st = time.time()
    re_df = pd.DataFrame(columns=["session_id","item_id",'dot', 'cos', 'eu'])
    i = 0
    for idx in _session_df.index:
        for candi in _candi_arr:
            dot = inner_product(_session_df.loc[idx],_item_df.loc[candi])
            cos = cosine_similarity(_session_df.loc[idx],_item_df.loc[candi])
            eu = eu_dist(_session_df.loc[idx],_item_df.loc[candi])
            re_df.loc[i] = [(idx),(candi),dot,cos,eu]
            i+=1
    et = time.time()
    print("done, time:",et-st)
    return re_df

In [ ]:
test = similarity_encoding(test_ses_vec,candidate.index,item_vec)

In [ ]:
test

15085